[package]
name = "rpx"
version = "1.0.0"
edition = "2021"
authors = ["Andrew S Aguiar <andrewaguiar6@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = '2.1.0'
clap = { version = "4.5.1", features = ["derive"] }
